# Generated by Django 5.2 on 2025-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
