# Generated by Django 5.2 on 2025-05-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EATING', '食習慣'), ('BODY', '健康・老化'), ('MIND', '性格・ストレス'), ('ECOLOGY', '環境汚染'), ('SURVIVAL', 'サバイバル'), ('WILD', 'ワイルドカード')], max_length=16)),
                ('text', models.CharField(max_length=255)),
                ('correct_yes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lp_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.CharField(max_length=3)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xday.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xday.quizsession')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifespan_years', models.IntegerField()),
                ('xday_date', models.DateField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xday.quizsession')),
            ],
        ),
    ]
